### ISSUE TITLE
License Restrictions?

### ISSUE THREAD

**Issue by derekjoos** [builttoroam/pipeline_templates#35]
Hey, I wanted to reach out and thank you for work on these pipeline templates. I'd like to utilize your templates in some of my pipelines, but couldn't find what license they're under. I found the notification on the website that suggested it is ok to use and modify, but it would be handy if you explicitly licensed the work. If you are really looking to share the templates, I would suggest the MIT license.

Github makes it pretty easy from here:
https://github.com/builttoroam/pipeline_templates/community/license/new?branch=master

https://choosealicense.com/no-permission/

**Comment by nickrandolph** [comment]
Sorry for the late response. All templates are free to use and change. I'll add an appropriate license shortly - thanks for highlighting this.

**Comment by nickrandolph** [comment]
Done - https://github.com/builttoroam/pipeline_templates/releases/tag/v0.7.2
Thanks @derekjoos
